export { MainPage } from './main-page'
export { MainLayout } from './layout'
export { Footer } from './footer'
export { Header } from './header'
export { MainSlider } from './main-slider'
export { Photography } from './photography'
export { Trust } from './trust'
export { Separator } from './separator'
export { Experience } from './experience'
export { Testimonials } from './testimonials'
export { BurgerMenu } from './burger-menu'
export { Blog } from './blog'
export { Article } from './article'
export { Projects } from './projects'
export { About } from './about'
export { Services } from './services'
export { FormMessage } from './form'
export { EstatePhotography } from './estate-photography'
export { HomeStaging } from './home-staging'
export { StagingNews } from './staging-news'

export * from './styles'
export * from './types'
